---
title: "Applied Survival Analysis Using R"
subtitle: "Chapter 07"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
    keep_md: no
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

```{r r-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen = 999)
options(max.print = "75")
set.seed(4321)

library(pacman)
p_load(asaur, survival, anytime, survminer)
```

```{r conflicts, include = FALSE}
# tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE,
                      echo = TRUE)
knitr::opts_knit$set(width = 75)
```

<!-- ----------------------------------------------------- -->

# 7.1 Assessing Goodness of Fit Using Residuals

```{r}
data(pharmacoSmoking)
str(pharmacoSmoking)
head(pharmacoSmoking)

pharmacoSmoking$priorAttemptsT <- pharmacoSmoking$priorAttempts
pharmacoSmoking$priorAttemptsT[pharmacoSmoking$priorAttempts > 20] <- 20

table(pharmacoSmoking$priorAttemptsT)

result.0.coxph <- coxph(Surv(ttr, relapse) ~ 1, data = pharmacoSmoking)
summary(result.0.coxph)

rr.0 <- residuals(result.0.coxph, type = "martingale")
```

```{r}
smoothSEcurve <- function(yy, xx) {
  # use after a call to "plot"
  # fit a lowess curve and 95% confidence interval curve
  
  # make list of x values
  xx.list <- min(xx) + ((0:100)/100)*(max(xx) - min(xx))
  # Then fit loess function through the points (xx, yy) at the listed values
  yy.xx <- predict(loess(yy ~ xx), se = T,
                   newdata = data.frame(xx = xx.list))
  lines(yy.xx$fit ~ xx.list, lwd = 2)
  lines(yy.xx$fit -
          qt(0.975, yy.xx$df)*yy.xx$se.fit ~ xx.list, lty = 2)
  lines(yy.xx$fit +
          qt(0.975, yy.xx$df)*yy.xx$se.fit ~ xx.list, lty = 2)
}
```

```{r}
par(mfrow=c(3,2))

plot(rr.0 ~ pharmacoSmoking$age)
smoothSEcurve(rr.0, pharmacoSmoking$age)
title("Martingale residuals\nversus age")

logAge <- log(pharmacoSmoking$age)
plot(rr.0 ~ logAge)
smoothSEcurve(rr.0, logAge)
title("Martingale residuals\nversus log age")

plot(rr.0 ~ pharmacoSmoking$priorAttemptsT)
smoothSEcurve(rr.0, pharmacoSmoking$priorAttemptsT)
title("Martingale residuals versus\nprior attempts")

logPriorAttemptsT <- log(pharmacoSmoking$priorAttemptsT + 1)
plot(rr.0 ~ logPriorAttemptsT)
smoothSEcurve(rr.0, logPriorAttemptsT)
title("Martingale residuals versus\nlog prior attempts")

plot(rr.0 ~ pharmacoSmoking$longestNoSmoke)
smoothSEcurve(rr.0, pharmacoSmoking$longestNoSmoke)
title("Martingale residuals versus\n longest period without smoking")

logLongestNoSmoke <- log(pharmacoSmoking$longestNoSmoke+1)
plot(rr.0 ~ logLongestNoSmoke)
smoothSEcurve(rr.0, logLongestNoSmoke)
title("Martingale residuals versus\n log of longest period without smoking")
```

```{r}
result.grp.coxph <- coxph(Surv(ttr, relapse) ~ grp, data = pharmacoSmoking)
result.step <- step(result.grp.coxph, 
                    scope = list(upper = ~ grp +
                                   gender + race + employment + yearsSmoking +
                                   levelSmoking + age + priorAttemptsT +
                                   logLongestNoSmoke, lower = ~grp) )

result.step

rr.final <- residuals(result.step, type="martingale")

par(mfrow=c(2,2))

plot(rr.final ~ pharmacoSmoking$age)
smoothSEcurve(rr.final, pharmacoSmoking$age)
title("Martingale residuals\nversus age")

plot(rr.final ~ pharmacoSmoking$grp)
title("Martingale residuals\nversus treatment group")

plot(rr.final ~ pharmacoSmoking$employment)
title("Martingale residuals\nversus employment")
```

```{r}
result.coxph <- coxph(Surv(ttr, relapse) ~ grp + employment + age, data = pharmacoSmoking)
coef.all <- result.coxph$coef[4]
coef.all

n.obs <- nrow(pharmacoSmoking)
jkbeta.vec <- rep(NA, n.obs)

for (i in 1:n.obs) {
  
  data.i <- pharmacoSmoking[-i, ]
  
  result.coxph.i <- coxph(Surv(ttr, relapse) ~ grp + employment + age, data = data.i)
  coef.i <- result.coxph.i$coef[4]
  
  jkbeta.vec[i] <- (coef.all - coef.i)
}

index.obs <- 1:n.obs
plot(jkbeta.vec ~ index.obs, type="h",
     xlab = "Observation", ylab = "Change in coefficient for age",
     cex.axis = 1.3, cex.lab = 1.3)
abline(h = 0)

# identify(jkbeta.vec ~ index.obs)

resid.dfbeta <- residuals(result.coxph, type = "dfbeta")

index.obs <- 1:n.obs

plot(resid.dfbeta[,4] ~ index.obs, type = "h",
     xlab = "Observation", ylab = "Change in coefficient")
abline(h = 0)

# identify(resid.dfbeta[,4] ~ index.obs)
```

# 7.2 Checking the Proportion Hazards Assumption

```{r}
data(pancreatic)
str(pancreatic)
head(pancreatic)
attach(pancreatic)

progression_d = anydate(as.character(progression))
onstudy_d = anydate(as.character(onstudy))
death_d = anydate(as.character(death))
progression_only = progression_d - onstudy_d
overall_survival = death_d - onstudy_d
pfs = pmin(progression_only, overall_survival)
pfs[is.na(pfs)] = overall_survival[is.na(pfs)]
pfs_month = pfs/30.5
```

```{r}
result.surv.LA <- survfit(Surv(pfs_month) ~ stage, subset = {stage == "LA"})
time.LA <- result.surv.LA$time
surv.LA <- result.surv.LA$surv
cloglog.LA <- log(-log(surv.LA))
logtime.LA <- log(time.LA)

result.surv.M <- survfit(Surv(pfs_month) ~ stage, subset = {stage == "M"})
time.M <- result.surv.M$time
surv.M <- result.surv.M$surv
cloglog.M <- log(-log(surv.M))
logtime.M <- log(time.M)

plot(cloglog.LA ~ logtime.LA, type = "s", col = "blue", lwd = 2)
lines(cloglog.M ~ logtime.M, col = "red", lwd = 2, type = "s")
legend("bottomright", legend=c("Locally advanced", "Metastatic"), col=c("blue","red"), lwd = 2)
```

```{r}
result.coxph <- coxph(Surv(pfs_month) ~ stage)
result.sch.resid <- cox.zph(result.coxph, transform = "km")

plot(result.sch.resid)

result.sch.resid

cox.zph(result.coxph, transform = "rank")
cox.zph(result.coxph, transform = "identity")
```

<!-- ----------------------------------------------------- -->

# Computing Environment

`r mu$session()`