---
title: "Applied Survival Analysis Using R"
subtitle: "Chapter 04"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
    keep_md: no
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

```{r r-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen = 999)
options(max.print = "75")
set.seed(4321)

library(pacman)
p_load(asaur, survival, anytime, survminer)
```

```{r conflicts, include = FALSE}
# tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE,
                      echo = TRUE)
knitr::opts_knit$set(width = 75)
```

<!-- ----------------------------------------------------- -->

# 4.1 Comparing Two Groups of Survival Times

```{r}
tt <- c(6, 7, 10, 15, 19, 25)
delta <- c(1, 0, 1, 1, 0, 1)
trt <- c(0, 0, 1, 0, 1, 1)
survdiff(Surv(tt, delta) ~ trt)
```

```{r}
data(pancreatic)
str(pancreatic)
head(pancreatic)

attach(pancreatic)

# progression free survival
progression_d = anydate(as.character(progression))
onstudy_d = anydate(as.character(onstudy))
death_d = anydate(as.character(death))

progression_only = progression_d - onstudy_d
overall_survival = death_d - onstudy_d

pfs = pmin(progression_only, overall_survival)

pfs[is.na(pfs)] = overall_survival[is.na(pfs)]

pfs_month = pfs/30.5

plot(survfit(Surv(pfs_month) ~ stage),
     xlab = "Time in months", ylab = "Survival probability",
     col = c("blue", "red"), lwd = 2)

legend ("topright", legend = c("Locally advanced", "Metastatic"), 
        col = c("blue", "red"), lwd = 2)


survdiff(Surv(pfs) ~ stage, rho = 0)

survdiff(Surv(pfs) ~ stage, rho = 1)
```

# 4.2 Stratified Tests

```{r}
data(pharmacoSmoking)
str(pharmacoSmoking)
head(pharmacoSmoking)

attach(pharmacoSmoking)

survdiff(Surv(ttr, relapse) ~ grp)

table(ageGroup2)

survdiff(Surv(ttr, relapse) ~ grp + strata(ageGroup2))
```

```{r}
lambda.mutant.0 <- 0.03
lambda.mutant.1 <- 0.03*0.55
lambda.wt.0 <- 0.03*0.2
lambda.wt.1 <- 0.03*0.2*0.55

tt.control.mutant <- rexp(25, rate=lambda.mutant.0)
tt.treat.mutant <- rexp(125, rate=lambda.mutant.1)
tt.control.wt <- rexp(125, rate=lambda.wt.0)
tt.treat.wt <- rexp(25, rate=lambda.wt.1)
ttAll <- c(tt.control.mutant, tt.treat.mutant, tt.control.wt, tt.treat.wt)
status <- rep(1, length(ttAll))
genotype <- c(rep("mutant", 150), rep("wt", 150))
trt <- c(rep(0, 25), rep(1, 125), rep(0, 125), rep(1, 25))

survdiff(Surv(ttAll, status) ~ trt)

plot(survfit(Surv(ttAll, status) ~ trt),
     xlab = "Time", ylab = "Survival probability",
     col = c("red", "blue"))

legend ("topright", legend = c("control", "treated"), 
        col = c("red", "blue"))

survdiff(Surv(ttAll, status) ~ trt + strata(genotype))

plot(survfit(Surv(ttAll, status) ~ trt + strata(genotype)),
     xlab = "Time", ylab = "Survival probability",
     col = c("red", "red", "blue", "blue"), lty = c("solid", "dashed"))

legend ("topright", legend = c("control mutant", "treated mutant",
                               "control wild", "treated wild"),
        col = c("red", "blue", "red", "blue"), 
        lty = c("solid", "solid", "dashed", "dashed"))
```

<!-- ----------------------------------------------------- -->

# Computing Environment

`r mu$session()`